### ISSUE TITLE
Crash when running in debug mode

### ISSUE THREAD

**Issue by neithanmo** [rust-fuzz/honggfuzz-rs#41] opened 2020-08-06 18:27 UTC
Not sure if this is an issue with rust-honggfuzz or rust or my sistem:
I am using:
- rustc 1.45.2 (d3fb005a3 2020-07-31)
- rustc 1.45.2 (d3fb005a3 2020-07-31)
- Pop_os 19:10(ubuntu base distro)

invoking:
`env HFUZZ_RUN_ARGS="--exit_upon_crash" cargo hfuzz run sound_producer my_input`

does not give any errors, but calling the same with:

`env HFUZZ_RUN_ARGS="--exit_upon_crash" cargo hfuzz run-debug sound_producer my_input`

got the following:

```
(lldb) command script import "/home/neithanmo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/etc/lldb_rust_formatters.py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 255, in <module>
    eFormatUnicode8 = _lldb.eFormatUnicode8
AttributeError: module '_lldb' has no attribute 'eFormatUnicode8'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
error: module importing failed: module '_lldb' has no attribute 'eFormatUnicode8'
  File "temp.py", line 1, in <module>
  File "/home/neithanmo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/etc/lldb_rust_formatters.py", line 1, in <module>
    import lldb
  File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 255, in <module>
    eFormatUnicode8 = _lldb.eFormatUnicode8
```

however, switching to nightly and running in debug mode gives me a different error:

`error: file specified in --source (-s) option doesn't exist: './lldb_commands'`

Someone has any advice on what the solution would be?

thanks in advance.

**Comment by PaulGrandperrin** [comment] 2021-01-16 14:22
Thanks for the report!
I'm sorry I wasn't able to respond at the time and now I can't reproduce.
I'm going to close it, but don't hesitate to open it again if needed :)

**Closed by PaulGrandperrin** 2021-01-16 14:22 UTC
